# triggered by schedule at 5am to try make sure it's done after the TS daily build
schedules:
- cron: '0 5 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: vscode_typescript_next_deploy_key
  displayName: 'Get the deploy key'

- bash: |
    npm run run-nightly
    npm publish

  displayName: 'Publish to NPM'