name: Bug Report
description: Suggest an idea for this project
title: "[Feature Request] "
labels:
  - "feature-request"
body:
  - type: markdown
    attributes:
      value: |
        To help us efficiently reviewing your feature request, please fill out this form.
  - type: checkboxes
    id: not
    attributes:
      label: Context
      options:
        - label: This issue is not a bug report. *(please use a different template for reporting a bug)*
          required: true
        - label: This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your feature request.
