###############################################################################################
#  Copyright (c) Microsoft Corporation. All rights reserved.
#  Licensed under the MIT License. See License.txt in the project root for license information.
###############################################################################################
name: $(Date:yyyyMMdd)$(Rev:.r)

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco
    - repository: vscode
      type: github
      name: microsoft/vscode
      ref: main
      endpoint: Monaco

parameters:
  - name: quality
    displayName: Quality
    type: string
    default: latest
    values:
      - latest
      - next

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: foobar
        testPlatforms:
          - name: Linux
            nodeVersions:
              - 16.14.2
          - name: MacOS
            nodeVersions:
              - 16.14.2
          - name: Windows
            nodeVersions:
              - 16.14.2
        testSteps:
          - checkout: vscode
          - script: dir $(Build.SourcesDirectory)
        buildSteps:
          - script: dir $(Build.SourcesDirectory)
        tag: ${{ parameters.quality }}
        publishPackage: false
        postPublishSteps:
          - script: dir .
        workingDirectory: $(Build.SourcesDirectory)
