###############################################################################################
#  Copyright (c) Microsoft Corporation. All rights reserved.
#  Licensed under the MIT License. See License.txt in the project root for license information.
###############################################################################################
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: '0 7 * * *'
    displayName: Daily release
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: monaco-editor-core
        workingDirectory: $(Build.SourcesDirectory)/dependencies/vscode/out-monaco-editor-core
        testPlatforms: []
        buildSteps:
          - script: npm ci
            displayName: Install NPM dependencies

          - script: yarn ts-node ./scripts/ci/prepare-monaco-editor-core nightly
            displayName: Setup, Build & Test monaco-editor-core

        tag: next
        publishPackage: true
        publishRequiresApproval: false

      - name: monaco-editor
        workingDirectory: $(Build.SourcesDirectory)/release
        testPlatforms: []
        buildSteps:
          - script: npm ci
            displayName: Install NPM dependencies

          - script: yarn ts-node ./scripts/ci/prepare-monaco-editor nightly
            displayName: Setup, Build & Test monaco-editor

        tag: next
        publishPackage: true
        publishRequiresApproval: false
